# Generated by Django 5.0 on 2024-09-23 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='default.JPG', upload_to='profile_pics'),
        ),
    ]
